---
dist: trusty
sudo: false
branches:
 only:
  - master
  - release
  # Build all feature branches
  - /^ff-/
  # Build all sandbox branches
  - /^sb-/
language: node_js
node_js: "8.15"
addons:
  apt:
    packages:
      - google-chrome-stable
      - unzip
before_install:
  - . ./scripts/setEnv.sh
  - npm install -g npm@5.6.0
  - npm install -g grunt-cli
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - ./canvas_modules/common-canvas/build.sh || travis_terminate 1;
  - ./canvas_modules/harness/build.sh || travis_terminate 1;
  - ./canvas_modules/harness/functional_test.sh || travis_terminate 1;
  - ./scripts/source_scan.sh || travis_terminate 1;
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/tagBuild.sh master last_success
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/publish_modules.sh
    on:
      branch: release
after_deploy:
  - ./scripts/bluemix_deploy.sh
notifications:
  slack:
    rooms:
      - watsondataplatform:XVNawCZULSfgMLsovgn2Stkp#wdp-canvas-builds
group: bluezone
