site_name: Elyra Canvas Guide
repo_url: https://github.com/elyra-ai/canvas
docs_dir: guide

theme: 
    name: material
    highlightjs: true
    palette:
        scheme: default
    features:
      - content.code.copy
      - content.action.edit

plugins:
    - search
    - awesome-pages

extra_css:
  - css/styles.css

extra_javascript:
  - js/links-in-new-tabs.js

edit_uri: edit/main/guide/

# Documentation and theme
copyright: 'Copyright &copy; 2024. Maintained by the Elyra Canvas Team., an open source project and all are welcome to contribute!<br> Maintained by the SPSS Modeler Team'

nav:
  - Home: index.md
  - Common Canvas Documentation: 2.0-Common-Canvas-Documentation.md
  - Canvas Editor: 2.0.1-Canvas-Editor.md
  - Nodes: 2.0.1.1-Nodes.md
  - Links: 2.0.1.2-Links.md
  - Palette: 2.0.2-Palette.md
  - Context Menu: 2.0.3-Context-Menu.md
  - Context Toolbar: 2.0.4-Context-Toolbar.md
  - Config Objects: 2.1-Config-Objects.md
  - Common Canvas Callbacks: 2.2-Common-Canvas-callbacks.md
  - Enabling Node Creation from External Object: 2.3-Enabling-node-creation-from-external-object.md
  - Canvas Controller API: 2.4-Canvas-Controller-API.md
  - Calling the Canvas Controller API: 2.4.0-Calling-the-Canvas-Controller-API.md
  - Style Specification: 2.4.1-Style-Specification.md
  - Decoration Specification: 2.4.2-Decoration-Specification.md
  - Object Structure used by API: 2.4.3-Object-structure-used-by-API.md
  - Notification Message Specification: 2.4.4-Notification-Message-Specification.md
  - Programmatically Creating new Canvas Nodes: 2.4.5-Programmatically-creating-new-canvas-nodes.md
  - Constructing a Read Only or Locked Canvas: 2.4.6-Constructing-a-read-only-or-locked-canvas.md
  - Commmand Stack API: 2.5-Command-Stack-API.md
  - Flow Validation API: 2.6-Flow-Validation-API.md
  - Customizing Node Layout Properties: 2.7-Customizing-Node-Layout-Properties.md
  - Context Menu Wrapper Documentation: 2.8-Context-Menu-Wrapper-Documentation.md
  - External Subflows Support: 2.9-External-Subflows-support.md
  - Common Properties Documentation: 3.0-Common-Properties-documentation.md
  - Common Properties Parameter Definition: 3.1-Common-Properties-Parameter-Definition.md
  - Common Properties UI Hints: 3.2-Common-Properties-UI-Hints.md
  - Common Properties Controls: 3.3-Common-Properties-Controls.md
  - Common Properties Conditions: 3.4-Common-Properties-Conditions.md
  - Common Properties Custom Components: 3.5-Common-Properties-Custom-Components.md
  - Common Properties Controller: 3.6-Common-Properties-Controller.md
  - Accessibility: 4.0-Accessibility.md
  - Styling: 5.0-Styling.md
  - Testing Guidelines for Development: 6.0-Testing-Guidelines-for-Development.md

markdown_extensions:
  - admonition:
  - codehilite:
  - extra:
  - pymdownx.magiclink:
  - pymdownx.inlinehilite:
  - pymdownx.highlight:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - sane_lists:
  - smarty:
  - toc:
      permalink: True
